BGK/BGK/Areas/Admin/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BGK.Models;
using BGK.Functions;

namespace BGK.Areas.Admin.Controllers
{
    [Controls("GalleryManagement")]
    public class GalleryController : Controller
    {
        private BGKEntities Db = new BGKEntities();
        public ActionResult Index(int num)
        {
            int take = 10;
            int skip = take * (num - 1);
            var gallery = Db.bgk_galeri;
            ViewBag.count = gallery.Count();
            ViewBag.take = take;
            return View(gallery.OrderByDescending(x => x.OlusturulmaTarihi).Skip(skip).Take(take).ToList());
        }
        public ActionResult Details(int num = 0)
        {
            var gallery = Db.bgk_galeri.Find(num);
            if (gallery == null)
                return Content("<script>$.BGK.ErrorModal('Bir sorun oluştu. Lütfen daha sonra tekrar deneyiniz.');</script>");
            return PartialView(gallery);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(bgk_galeri gallery)
        {
            if (ModelState.IsValid)
            {
                gallery.Seo = gallery.Adi.ConvertSeo();
                gallery.OlusturulmaTarihi = DateTime.Now;
                Db.bgk_galeri.Add(gallery);
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gallery);
        }
        public ActionResult Edit(int num = 0)
        {
            bgk_galeri gallery = Db.bgk_galeri.Find(num);
            if (gallery == null)
                return HttpNotFound();
            return View(gallery);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(bgk_galeri gallery)
        {
            if (ModelState.IsValid)
            {
                gallery.Seo = gallery.Adi.ConvertSeo();
                Db.Entry(gallery).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gallery);
        }
        public ActionResult ChangeApproval(int num = 0)
        {
            string result = "";
            bgk_galeri gallery = Db.bgk_galeri.Find(num);
            if (gallery != null)
            {
                gallery.Onay = gallery.Onay == true ? false : true;
                result = gallery.Onay == true ? "Galeri başarıyla onaylandı." : "Galerinin onayı başarıyla kaldırıldı.";
                Db.SaveChanges();
            }
            return Content("<script>$.BGK.SuccessModal('" + result + "');</script>");
        }
        public ActionResult Delete(int num = 0)
        {
            bgk_galeri gallery = Db.bgk_galeri.Find(num);
            if (gallery == null)
                return Content("<script>$.BGK.ErrorModal('Bir sorun oluştu. Lütfen daha sonra tekrar deneyiniz.');</script>");
            return PartialView("DeleteActions", new delete_action() { Id = num, Title = gallery.Adi, Message = "Bu galeriyi ve bu galeriye ait tüm resimleri silmek istediğinizden emin misiniz?" });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(delete_action model)
        {
            bgk_galeri gallery = Db.bgk_galeri.Find(model.Id);
            foreach (var image in gallery.bgk_galeri_resim.ToList())
            {
                Db.bgk_galeri_resim.Remove(image);
            }
            Db.bgk_galeri.Remove(gallery);
            Db.SaveChanges();
            return Content("<script>$.BGK.SuccessModal('Galeri başarılı bir şekilde silindi.', function (){ window.location.href='" + Url.Action("index") + "'; }, 1500);</script>");
        }
        protected override void Dispose(bool disposing)
        {
            Db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BGK/BGK/Areas/Admin/Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BGK.Models;
using BGK.Functions;

namespace BGK.Areas.Admin.Controllers
{
    [Controls("PollManagement")]
    public class PollController : Controller
    {
        private BGKEntities Db = new BGKEntities();
        public ActionResult Index(int num)
        {
            int take = 10;
            int skip = take * (num - 1);
            var poll = Db.bgk_anket;
            ViewBag.count = poll.Count();
            ViewBag.take = take;
            return View(Db.bgk_anket.OrderBy(x => x.Sira).Skip(skip).Take(take).ToList());
        }
        public ActionResult Details(int num = 0)
        {
            bgk_anket bgk_anket = Db.bgk_anket.Find(num);
            if (bgk_anket == null)
                return HttpNotFound();
            return View(bgk_anket);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(bgk_anket bgk_anket)
        {
            if (ModelState.IsValid)
            {
                Db.bgk_anket.Add(bgk_anket);
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bgk_anket);
        }
        public ActionResult Edit(int num = 0)
        {
            bgk_anket bgk_anket = Db.bgk_anket.Find(num);
            if (bgk_anket == null)
                return HttpNotFound();
            return View(bgk_anket);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(bgk_anket bgk_anket)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(bgk_anket).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bgk_anket);
        }
        public ActionResult AddOption(int num = 0)
        {
            bgk_anket bgk_anket = Db.bgk_anket.Find(num);
            if (bgk_anket == null)
                return Content("<script>$.BGK.ErrorModal('Bir sorun oluştu. Lütfen daha sonra tekrar deneyiniz.');</script>");
            ViewBag.pollName = bgk_anket.Soru;
            bgk_anket_secenek option = new bgk_anket_secenek() { AnketID = num };
            return PartialView(option);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOption(bgk_anket_secenek bgk_anket_secenek)
        {
            if (ModelState.IsValid)
            {
                Db.bgk_anket_secenek.Add(bgk_anket_secenek);
                Db.SaveChanges();
                return Content("<script>$.BGK.SuccessModal('Seçenek başarılı bir şekilde eklendi.', function (){ window.location.reload(); }, 1500);</script>");
            }
            return Content("<font color=\"red\">Eksik bıraktığınız alan var!</font>");
        }
        public ActionResult DeleteOption(int num = 0)
        {
            bgk_anket_secenek bgk_anket_secenek = Db.bgk_anket_secenek.Find(num);
            var poll = bgk_anket_secenek.bgk_anket;
            if (bgk_anket_secenek == null)
                return Content("<script>$.BGK.ErrorModal('Bir sorun oluştu. Lütfen daha sonra tekrar deneyiniz.');</script>");
            return PartialView("DeleteActions", new delete_action() { Id = num, Title = "Seçenek Sil", Message = "Bu seçeneği silmek istediğinizden emin misiniz?" });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteOption(delete_action model)
        {
            bgk_anket_secenek option = Db.bgk_anket_secenek.Find(model.Id);
            foreach (var selection in option.bgk_anket_secim)
            {
                Db.bgk_anket_secim.Remove(selection);
            }
            Db.bgk_anket_secenek.Remove(option);
            Db.SaveChanges();
            return Content("<script>$.BGK.SuccessModal('Seçenek başarılı bir şekilde silindi.', function (){ window.location.reload(); }, 1500);</script>");
        }
        public ActionResult ChangeApproval(int num = 0)
        {
            string result = "";
            bgk_anket poll = Db.bgk_anket.Find(num);
            if (poll != null)
            {
                poll.Onay = !poll.Onay;
                result = poll.Onay ? "Anket başarıyla onaylandı." : "Anketin onayı başarıyla kaldırıldı.";
                Db.SaveChanges();
            }
            return Content("<script>$.BGK.SuccessModal('" + result + "');</script>");
        }
        public ActionResult Delete(int num = 0)
        {
            bgk_anket bgk_anket = Db.bgk_anket.Find(num);
            if (bgk_anket == null)
                return Content("<script>$.BGK.ErrorModal('Bir sorun oluştu. Lütfen daha sonra tekrar deneyiniz.');</script>");
            return PartialView("DeleteActions", new delete_action() { Id = num, Title = bgk_anket.Soru, Message = "Bu anketi silmek istediğinizden emin misiniz?" });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(delete_action model)
        {
            bgk_anket bgk_anket = Db.bgk_anket.Find(model.Id);
            foreach (var option in bgk_anket.bgk_anket_secenek.ToList())
	        {
                foreach (var selection in option.bgk_anket_secim.ToList())
	            {
		            Db.bgk_anket_secim.Remove(selection);
	            }
		        Db.bgk_anket_secenek.Remove(option);
	        }
            Db.bgk_anket.Remove(bgk_anket);
            Db.SaveChanges();
            return Content("<script>$.BGK.SuccessModal('Anket başarılı bir şekilde silindi.', function (){ window.location.href='" + Url.Action("index") + "'; }, 1500);</script>");
        }
        protected override void Dispose(bool disposing)
        {
            Db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BGK/BGK/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BGK.Models;
using BGK.Functions;

namespace BGK.Areas.Admin.Controllers
{
    [Controls("PostManagement")]
    public class PostController : Controller
    {
        private BGKEntities Db = new BGKEntities();
        public ActionResult Index(int num)
        {
            int take = 10;
            int skip = take * (num - 1);
            int categoryID = Convert.ToInt32(Request.QueryString["categoryID"]);
            int memberID = Convert.ToInt32(Request.QueryString["memberID"]);
            var post = !string.IsNullOrEmpty(Request.QueryString["categoryID"]) ? Db.bgk_yazi.Where(x => x.KategoriID == categoryID) : string.IsNullOrEmpty(Request.QueryString["memberID"]) ? Db.bgk_yazi : Db.bgk_yazi.Where(x => x.UyeID == memberID);
            ViewBag.count = post.Count();
            ViewBag.take = 10;
            return View(post.OrderByDescending(x => x.YazimTarihi).Skip(skip).Take(take).ToList());
        }
        public ActionResult Details(int num = 0)
        {
            bgk_yazi post = Db.bgk_yazi.Find(num);
            if (post == null)
                return Content("<script>$.BGK.ErrorModal('Bir sorun oluştu. Lütfen daha sonra tekrar deneyiniz.');</script>");
            return PartialView(post);
        }
        public ActionResult Create()
        {
            ViewBag.KategoriID = new SelectList(Db.bgk_kategori, "Id", "Adi");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(bgk_yazi post)
        {
            if (ModelState.IsValid)
            {
                int memberID = (int)Session["memberID"];
                post.UyeID = memberID;
                post.Seo = post.Baslik.ConvertSeo();
                post.YazimTarihi = DateTime.Now;
                post.Okunma = 0;
                Db.bgk_yazi.Add(post);
                Db.SaveChanges();
                return RedirectToAction("index");
            }
            ViewBag.KategoriID = new SelectList(Db.bgk_kategori, "Id", "Adi");
            return View(post);
        }
        public ActionResult Edit(int num = 0)
        {
            bgk_yazi post = Db.bgk_yazi.Find(num);
            if (post == null)
                return HttpNotFound();
            ViewBag.KategoriID = new SelectList(Db.bgk_kategori, "Id", "Adi", post.KategoriID);
            return View(post);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(bgk_yazi post)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(post).State = EntityState.Modified;
                post.Seo = post.Baslik.ConvertSeo();
                Db.SaveChanges();
                return RedirectToAction("index");
            }
            ViewBag.KategoriID = new SelectList(Db.bgk_kategori, "Id", "Adi", post.KategoriID);
            return View(post);
        }
        public ActionResult ChangeApproval(int num = 0)
        {
            string result = "";
            bgk_yazi post = Db.bgk_yazi.Find(num);
            if (post != null)
            {
                result = post.Onay ? "Yazının onayı başarıyla kaldırıldı." : "Yazı başarıyla onaylandı.";
                post.Onay = !post.Onay;
                Db.SaveChanges();
            }
            return Content("<script>$.BGK.SuccessModal('" + result + "');</script>");
        }
        public ActionResult Delete(int num = 0)
        {
            bgk_yazi post = Db.bgk_yazi.Find(num);
            if (post == null)
                return Content("<script>$.BGK.ErrorModal('Bir sorun oluştu. Lütfen daha sonra tekrar deneyiniz.');</script>");
            return PartialView("DeleteActions", new delete_action() { Id = num, Title = post.Baslik, Message = "Bu yazıyı ve bu yazıya ait yorumları silmek istediğinizden emin misiniz?" });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(delete_action model)
        {
            bgk_yazi post = Db.bgk_yazi.Find(model.Id);
            BGKFunction.DeletePost(post);
            Db.bgk_yazi.Remove(post);
            Db.SaveChanges();
            return Content("<script>$.BGK.SuccessModal('Yazı başarılı bir şekilde silindi.', function (){ window.location.href='" + Url.Action("index") + "'; }, 1500);</script>");
        }
        protected override void Dispose(bool disposing)
        {
            Db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BGK/BGK/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BGK.Models;
using BGK.Functions;

namespace BGK.Controllers
{
    [MaintenanceControl]
    public class GalleryController : Controller
    {
        private BGKEntities Db = new BGKEntities();
        public ActionResult Index(int page)
        {
            int take = 7;
            int skip = take * (page - 1);
            var gallery = Db.bgk_galeri.Where(x => x.Onay == true).OrderByDescending(x => x.OlusturulmaTarihi);
            ViewBag.Title = "Galeri";
            ViewBag.count = gallery.Count();
            ViewBag.take = take;
            return View(gallery.Skip(skip).Take(take).ToList());
        }
        public ActionResult Images(string seo, int page)
        {
            var gallery = Db.bgk_galeri.SingleOrDefault(x => x.Seo == seo && x.Onay == true);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            else
            {
                var images = gallery.bgk_galeri_resim.Where(x => x.Onay == true).OrderBy(x => x.Sira);
                int take = 7;
                int skip = take * (page - 1);
                ViewBag.Title = gallery.Adi + " Galerisindeki Resimler";
                ViewBag.count = images.Count();
                ViewBag.take = take;
                ViewBag.seo = seo;
                return View(images.Skip(skip).Take(take).ToList());
            }
        }
        public ActionResult View(string seo, int id)
        {
            var image = Db.bgk_galeri_resim.Find(id);
            if (image == null || image.Onay == false || image.bgk_galeri.Seo != seo)
                return HttpNotFound();
            else
                return View(image);
        }
        protected override void Dispose(bool disposing)
        {
            Db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BGK/BGK/Views/Widget/AboutBGK.cshtml
<div class="table">
    <div class="title">Kısaca BGK</div>
    <div class="content" style="text-align: justify;">
        Bilgi Güvenliği Kulübü, bilgisayar ve bilişim dünyasına ilgi duyan ve yenilikçi fikirlerini düşünmekle kalmayıp uygulamak isteyen Erciyes Üniversitesi girişimci öğrencileri tarafından kurulmuş bir öğrenci kulübüdür.
        <br /><br />  
        Gelişen yeni fikir ve tekniklerle Erciyes Üniversitesi'nin bilgi güvenliğini sağlamak ve eksiklerini tamamlamak, teknoloji dünyasıyla ilgili araştırmalar yapmak.
    </div>
</div>

BGK/BGK/Views/Widget/Gallery.cshtml
@model IEnumerable<bgk_galeri_resim>

<div class="table">
    <div class="title">Galeriden
        <span><a href="@Url.Action("Index", "Gallery")">Tümü</a></span>
    </div>
    <div class="content">
        @foreach (var image in Model)
        {
            <img src="@BGKFunction.GetFile(image.bgk_dosya)" width="100" />
        }
    </div>
</div>

BGK/BGK/Views/Widget/MemberMenu.cshtml
@{
    int memberID = Convert.ToInt32(Session["memberID"]);
    var member = BGKFunction.GetMyAccount();
    int missionCount = member.bgk_gorev_uye.Where(x => x.Onay == null).Count();
    int notificationCount = member.bgk_bildirim.Where(x => x.Okundu == false).Count();
}
<script type="text/javascript">
    var title = document.title;
    $(function () {
        $("div#notifications").css({
            "left": $("div#membership div.content").position().left,
            "width": $("div#membership").width(),
            "height": $("div#membership").height() - 53
        });
        setInterval(function () {
            $.post("@Url.Action("LastLoginDate", "Member")", {}, function () { });
            var count = 0;
            $.post("@Url.Action("MemberMessageCount", "Member")", { id: "@memberID" }, function (msg) {
                $("label.messagecount").html(msg == "0" ? "" : "<b>(" + msg + ")</b>");
                count += parseInt(msg);
            });
            $.post("@Url.Action("MyNotificationCount", "Member")", { }, function (msg) {
                $("label.notificationcount").html(msg == "0" ? "" : "<b>(" + msg + ")</b>");
                count += parseInt(msg);
            });
            document.title = (count == 0 ? "" : "(" + count + ") ") + title;
        }, 1000);
    });
    function ShowNotifications() {
        $.post("@Url.Action("MyNotifications", "Member")", {}, function (msg) {
            $("div#notifications").html(msg).stop().slideToggle();
        });
    }
</script>
<div id="membership" class="table">
    <div class="content" style="text-align: center;">
        Merhaba <b><a href="@Url.Action("Details", "Member", new { id = Session["memberID"] })">@member.AdSoyad (@Html.Raw(member.GetMemberRole().Adi))</a></b><br />
        <a href="@Url.Action("Messages", "Member")">Mesajlarım <label class="messagecount"></label></a> -
        <a href="javascript:void(0);" onclick="ShowNotifications();">Bildirimler <label class="notificationcount"></label></a> -
        @if (member.Yetki == 100)
        {
            <a href="@Url.Action("", "", new { area = "Admin" })" target="_blank">Yönetim</a><text> -</text>
        }
        <a href="javascript:void(0);" onclick="$.BGK.Modal('@Url.Action("Logout", "Member")');">Çıkış</a>
        <div id="notifications" style="position: absolute; display: none; background-color: #fff; border-top: 2px solid #ddd;">bildirimler</div>
    </div>

    <div class="title">Gruplar
        <span>@Html.ActionLink("Tümü", "Index", "Group")</span>
    </div>
    <div class="content">
        @foreach (var group in member.bgk_grup_uye.ToList())
        {
            <a href="@Url.Action("details", "group", new { id = group.GrupID, seo = group.bgk_grup.Adi.ConvertSeo() })">@group.bgk_grup.Adi</a><br />
        }
    </div>
    
    <div class="title">Görev Kategorileri</div>
    <div class="content">
        @Html.ActionLink("Tüm Kategoriler", "categories", "mission")<br />
        @Html.ActionLink("Aboneliklerim", "subscribedcategories", "mission")<br />
        @Html.ActionLink("Oluşturduğum Kategoriler", "mycategories", "mission")
    </div>

    <div class="title">Görevler</div>
    <div class="content">
        <a href="@Url.Action("MyMissions", "Mission")">@Html.Raw(missionCount == 0 ? "Görevlerim" : "<b>Görevlerim (" + missionCount + ")</b>")</a><br />
        @Html.ActionLink("Sıradaki Görevler", "list", "mission")<br />
        @Html.ActionLink("Oluşturduğum Görevler", "createdmissions", "mission")
    </div>
</div>

BGK/BGK/Views/Widget/PinnedPosts.cshtml
@model IEnumerable<bgk_yazi>
@{
    int i = 0;    
}
@if (Model.Count() != 0)
{
    <script type="text/javascript">
        $(function () {
            var postCount = $("div.notices div.pages input").length;
            var index = 0;
            setInterval(function () {
                $("div.notices div.pages input:eq(" + index++ % postCount + ")").click();
            }, 7000);
            function ChangePost(i) {
                $("div.notices div.content").hide();
                $("div.notices div.content:eq(" + i % postCount + ")").fadeIn(500);
                index = ++i;
            }
            $("div.notices div.pages input:radio[name='page']").change(function () {
                ChangePost($(this).val());
            });
            $("div.notices div.pages input:eq(" + index + ")").click();
        });
    </script>
    <div class="table notices" style="height: 250px;">
        @foreach (var post in Model)
        {
            <div class="content" style="display: none; height: 220px;">
                <h3>@post.Baslik</h3>
                @Html.Raw(post.Ozet)
            </div>
        }
        <div class="pages" style="text-align: center;">
            @foreach (var post in Model)
            {
                <input type="radio" value="@(i++)" name="page" title="@post.Baslik" />
            }
        </div>
    </div>
}

BGK/BGK/Views/Widget/Poll.cshtml
@model bgk_anket

<div class="table">
    <div class="title">Anket
        <span><a href="@Url.Action("Index", "Poll")">Tümü</a></span>
    </div>
    <div class="content">
        @if (BGKFunction.IsVoted(Model.Id) || Model.BitisTarihi < DateTime.Now)
        {
            Html.RenderAction("Results", "Poll", new { id = Model.Id });
        }
        else
        {
            <div id="@("poll_" + Model.Id)" class="poll">
                <b>@Model.Soru</b><br />
                @foreach (var option in Model.bgk_anket_secenek.OrderBy(x => x.Sira).ToList())
                {
                    if (Model.CokluSecim)
                    {
                        <div>
                            <input type="checkbox" id="@("option_" + option.Id + "")" name="@("poll_" + Model.Id)" value="@option.Id" />
                            <label for="@("option_" + option.Id)">@option.Adi</label>
                        </div>
                    }
                    else
                    {
                        <div>
                            <input type="radio" id="@("option_" + option.Id)" name="@("poll_" + Model.Id)" value="@option.Id" />
                            <label for="@("option_" + option.Id)">@option.Adi</label>
                        </div>
                    }
                }
                <div class="warning"></div>
                @Html.Button("Gönder", new { id = Model.Id, type = "submit", style = "float: right;" })
            </div>
        }
    </div>
</div>

BGK/BGK/Views/Widget/Posts.cshtml
@model IEnumerable<bgk_yazi>

<div class="table">
    <div class="title">Neler Okunuyor?
        <span><a href="@Url.Action("Popular", "Post")">Tümü</a></span>
    </div>
    <div class="content" style="padding: 0;">
        <div class="posts">
            @foreach (var post in Model)
            {
                <a href="@Url.Action("Details", "Post", new { seo = post.Seo, id = post.Id })">
                    <ul>
                        <li>@post.Baslik</li>
                        <li>@post.Icerik.GetSummary(100)</li>
                    </ul>
                </a>
            }
        </div>
    </div>
</div>

BGK/BGK/Views/Widget/Search.cshtml
@model bgk_search
<script type="text/javascript">
    $(function () {
        $(window).keyup(function (e) {
            if (e.keyCode == 13 && $("#search input[type=text]").is(":focus")) {
                window.location.href = "@Url.Action("Search", "Post")?q=" + $("#search input[type=text]").val() + "";
            }
        });
    });
</script>
<div class="table">
    <div id="search" class="content">
        @Html.TextBoxFor(model => model.Query, new { placeholder = "Aramak istediğin kelimeyi yaz ve Enter'la..." })
    </div>
</div>